name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/develop.txt
      - name: Run test
        run: pytest
      - uses: akhileshns/heroku-deploy@v3.0.0
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "walmart-api-inawrath"
          heroku_email: ${{ secrets.EMAIL_HEROKU }}
          usedocker: true
          dontuseforce: true
