name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.9'
    - name: Install Package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/develop.txt
    - name: Run test
      run: pytest
